# Generated by Django 5.0.1 on 2024-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiseweight', 'Cruiseweight')], max_length=20)),
                ('weight_limit', models.IntegerField(default=500)),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('returning', 'Returning')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
