# Generated by Django 5.0.1 on 2024-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationID', models.IntegerField()),
                ('droneID', models.IntegerField()),
                ('loaded_item_name', models.CharField(max_length=100)),
                ('drone_availability', models.CharField(max_length=20)),
                ('drone_battery_life', models.IntegerField()),
            ],
        ),
    ]
